# Generated by Django 5.0.6 on 2024-09-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_torru", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motiondesign",
            name="video2",
            field=models.FileField(
                blank=True, upload_to="videos/", verbose_name="Видео 2"
            ),
        ),
    ]
