# Generated by Django 5.0.6 on 2024-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_torru", "0002_alter_motiondesign_video2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motiondesign",
            name="video1",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="Видео 1"
            ),
        ),
        migrations.AlterField(
            model_name="motiondesign",
            name="video2",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="Видео 2"
            ),
        ),
    ]
